/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ListingsIndexRouteImport } from './routes/listings/index'
import { Route as ListingsIdRouteImport } from './routes/listings/$id'
import { Route as ListingsTypeUnitTypeRouteImport } from './routes/listings/type/$unitType'
import { Route as ListingsInLocationRouteImport } from './routes/listings/in/$location'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIndexRoute = ListingsIndexRouteImport.update({
  id: '/listings/',
  path: '/listings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsIdRoute = ListingsIdRouteImport.update({
  id: '/listings/$id',
  path: '/listings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsTypeUnitTypeRoute = ListingsTypeUnitTypeRouteImport.update({
  id: '/listings/type/$unitType',
  path: '/listings/type/$unitType',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsInLocationRoute = ListingsInLocationRouteImport.update({
  id: '/listings/in/$location',
  path: '/listings/in/$location',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/': typeof ListingsIndexRoute
  '/listings/in/$location': typeof ListingsInLocationRoute
  '/listings/type/$unitType': typeof ListingsTypeUnitTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings': typeof ListingsIndexRoute
  '/listings/in/$location': typeof ListingsInLocationRoute
  '/listings/type/$unitType': typeof ListingsTypeUnitTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/listings/$id': typeof ListingsIdRoute
  '/listings/': typeof ListingsIndexRoute
  '/listings/in/$location': typeof ListingsInLocationRoute
  '/listings/type/$unitType': typeof ListingsTypeUnitTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/listings/$id'
    | '/listings/'
    | '/listings/in/$location'
    | '/listings/type/$unitType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/listings/$id'
    | '/listings'
    | '/listings/in/$location'
    | '/listings/type/$unitType'
  id:
    | '__root__'
    | '/'
    | '/listings/$id'
    | '/listings/'
    | '/listings/in/$location'
    | '/listings/type/$unitType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListingsIdRoute: typeof ListingsIdRoute
  ListingsIndexRoute: typeof ListingsIndexRoute
  ListingsInLocationRoute: typeof ListingsInLocationRoute
  ListingsTypeUnitTypeRoute: typeof ListingsTypeUnitTypeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/': {
      id: '/listings/'
      path: '/listings'
      fullPath: '/listings/'
      preLoaderRoute: typeof ListingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/$id': {
      id: '/listings/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof ListingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/type/$unitType': {
      id: '/listings/type/$unitType'
      path: '/listings/type/$unitType'
      fullPath: '/listings/type/$unitType'
      preLoaderRoute: typeof ListingsTypeUnitTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings/in/$location': {
      id: '/listings/in/$location'
      path: '/listings/in/$location'
      fullPath: '/listings/in/$location'
      preLoaderRoute: typeof ListingsInLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListingsIdRoute: ListingsIdRoute,
  ListingsIndexRoute: ListingsIndexRoute,
  ListingsInLocationRoute: ListingsInLocationRoute,
  ListingsTypeUnitTypeRoute: ListingsTypeUnitTypeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
